global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "unbound"
    static_configs:
      - targets: ["host.docker.internal:9167"]

  - job_name: "traefik"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["traefik:8080"]
